apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: aws-registry-credential-cron
spec:
  schedule: "* */8 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          serviceAccountName: <XXXXXXXXXXX-SERVICE-ACCCOUNT-THAT-CAN-DELETE-AND-UPDATE-SECRETS>
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          volumes:
            - name: docker-sock-volume
              hostPath:
                # location on host
                path: /var/run/docker.sock
          containers:
          - name: credomatorix
            image: qubusp/credomatorix
            volumeMounts:
              - mountPath: /var/run/docker.sock
                name: docker-sock-volume
            imagePullPolicy: IfNotPresent
            env:
               - name: aws_access_key_id
                 valueFrom:
                   secretKeyRef:
                     name: aws_credentials
                     key: username
               - name: aws_secret_access_key
                 valueFrom:
                   secretKeyRef:
                    name: aws_credentials
                    key: password
               - name: K8S_CRED
                 valueFrom:
                   secretKeyRef:
                    name: k8s_credentials
                    key: cert
